---
- hosts: localhost
  connection: local
  vars:
    location: northeurope
    domain_sub: automationfunsantaz
    virtual_network_name: automationNetwork
    subnet: Servers

  vars_prompt:
    - name: resource_group
      prompt: "Type the name of your Azure Resource Group"
      private: no

  tasks:
  # Start All Virtual Machines
  - name: Start VM ansible
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "ansible"
      state: present
      started: true
      
  - name: Start VM server1
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "server1"
      state: present
      started: true

  - name: Stop VM server2
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      allocated: no
      name: "server2"
      state: present
      started: false
  
  - name: Start VM server3
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "server3"
      state: present
      started: true

  - name: Stop VM server4
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      allocated: no
      name: "server4"
      state: present
      started: false