---
- hosts: localhost
  connection: local

  vars_prompt:
    - name: resource_group
      prompt: "Type the name of your Azure Resource Group"
      private: no

  tasks:
# Stop All Virtual Machines
  - name: Start VM ansible
    azure_rm_virtualmachine:
      resource_group: "{{ resource_group }}"
      name: "{{ item }}"
      state: present
      started: true
    loop:
      - ansible
      - server1
      - server2
      - server3
      - server4
    async: 1000
    poll: 0
    register: start_all

  - name: Wait for VMs to start
    async_status:
      jid: "{{ item.ansible_job_id }}"
    register: job_result
    until: job_result.finished
    retries: 100
    delay: 5
    with_items: "{{ start_all.results }}"