---
- name: Automation Class Student
  hosts: "{{ student | default([]) }}"
  vars:
    ansible_connection: ssh
    ansible_shell_type: powershell
    ansible_host_key_checking: false
    ansible_become_method: runas
    ansible_become_user: "SYSTEM"
    #ansible_become_password: "{{ ansible_password }}"
    #ansible_become_flags: logon_type=new_credentials logon_flags=netcredentials_only

  tasks:
    - name: Install WSL
      ansible.windows.win_powershell:
        script: |
          wsl.exe --install
      become: true
