---
- hosts: localhost
  vars:

  vars_prompt:
    - name: password
      prompt: Password
      private: no

  environment:
    VMWARE_USER: administrator@vsphere.local
    VMWARE_HOST: vcenter.ansible.local
    VMWARE_VALIDATE_CERTS: no
    VMWARE_PASSWORD: "{{ password }}"

  tasks:
    - name: Get a list of all the datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: existing_datacenters

    - name: Debug
      debug:
        var: "{{ existing_datacenters }}"

#    - name: Set my_datacenter_folder
#      set_fact:
#        my_datacenter_folder: '{{ my_folders.value|selectattr("type", "equalto", "DATACENTER")|first}}'

    - name: Create datacenter Datacenter
      vmware.vmware_rest.vcenter_datacenter:
        name: Datacenter