---
- hosts: localhost
  vars:

  vars_prompt:
    - name: password
      prompt: Password
      private: no

  environment:
    VMWARE_USER: administrator@vsphere.local
    VMWARE_HOST: vcenter.ansible.local
    VMWARE_VALIDATE_CERTS: no
    VMWARE_PASSWORD: "{{ password }}"

  tasks:
    - name: Get a list of all the datacenters
      vmware.vmware_rest.vcenter_datacenter_info:
      register: existing_datacenters

    - name: Debug
      debug:
        var: "{{ existing_datacenters }}"

