---
- hosts: localhost
  connection: local
  vars:
    location: northeurope
    virtualnetwork_name: automationNetwork
    subnet: Servers
    tag_owner: arrow
    tag_project: ansibletraining

  vars_prompt:
    - name: resourcegroup_input
      prompt: "Type the name of your Azure Resource Group"
      private: no
    - name: adminUser
      prompt: "Type the name of your root/administrator account"
      private: no
    - name: adminPassword
      prompt: "Type the password of your root/administrator account"
      private: no

  tasks:
    - name: Azure Resource Group
      include_role:
        name: jesperberth.az_resourcegroup
      vars:
        resourcegroup: "{{ resourcegroup_input }}"
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"

    - name: Azure Virtual Network
      include_role:
        name: jesperberth.az_virtualnetwork
      vars:
        resourcegroup: "{{ resourcegroup_input }}"
        cidr: 10.1.0.0/16
        subnet_name: Servers
        subnet_cidr: 10.1.0.0/24
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"
        
    - name: Azure Network Security Group
      include_role:
        name: jesperberth.az_securitygroup
      vars:
        resourcegroup: "{{ resourcegroup_input }}"
        networksecuritygroup_name: "{{ item.networksecuritygroup_name }}"
        rulename: "{{ item.rulename }}"
        ruleprotocol: "{{ item.ruleprotocol }}"
        rulesourceaddress: "{{ item.rulesourceaddress }}"
        ruledestinationportrange: "{{ item.ruledestinationportrange }}"
        ruleaccess: "{{ item.ruleaccess }}"
        rulepriority: "{{ item.rulepriority }}"
        ruledirection: "{{ item.ruledirection }}"
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"
      loop:
        - { networksecuritygroup_name: 'SG_Network', rulename: 'AllowSSH',  ruleprotocol: 'Tcp', rulesourceaddress: '0.0.0.0/0', ruledestinationportrange: '22', ruleaccess: 'Allow', rulepriority: '102', ruledirection: 'Inbound' }
        - { networksecuritygroup_name: 'SG_Network', rulename: 'AllowRDP',  ruleprotocol: 'Tcp', rulesourceaddress: '0.0.0.0/0', ruledestinationportrange: '3389', ruleaccess: 'Allow', rulepriority: '103', ruledirection: 'Inbound' }
          
    - name: Azure VM
      include_role:
        name: jesperberth.az_vm
      vars:
        vmname: "{{ item.vmname }}"
        virtualnetwork_name: "{{ virtualnetwork_name }}"
        networksecuritygroup_name: "SG_Network"
        vmsize: "Standard_A1_v2"
        ostype: "{{ item.ostype }}"
        azurevmuser: jesbe
        azurevmpw: "{{ adminPassword }}"
        offer: "{{ item.offer}}"
        publisher: "{{ item.publisher}}"
        sku: "{{ item.sku}}"
        version: "{{ item.version}}"
      loop:
        - { 'vmname': 'server1', 'ostype': 'Linux', 'offer': 'RHEL', 'publisher': 'RedHat', 'sku': '8', 'version': 'latest' }
        - { 'vmname': 'server2', 'ostype': 'Windows', 'offer': 'WindowsServer', 'publisher': 'MicrosoftWindowsServer', 'sku': '2019-Datacenter', 'version': 'latest' }
      async: 1000
      poll: 0
      register: create_vm

    - name: Wait for Virtual Machines
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 5
      with_items: "{{ create_vm.results }}"