---
- hosts: localhost
  connection: local
  vars:
    location: northeurope
    virtual_network_name: automationNetwork
    subnet: Servers
    tag_project: ansibletraining

  vars_prompt:
    - name: resourcegroup
      prompt: "Type the name of your Azure Resource Group"
      private: no
    - name: adminUser
      prompt: "Type the name of your root/administrator account"
      private: no
    - name: adminPassword
      prompt: "Type the password of your root/administrator account"
      private: no

  tasks:
    - name: Azure Resource Group
      include_role:
        name: jesperberth.az-resourcegroup

    - name: Azure Virtual Network
      include_role:
        name: jesperberth.az-virtualnetwork

    - name: Azure Network Security Group
      include_role:
        name: jesperberth.az-securitygroup
          