---
- hosts: localhost
  connection: local
  become: yes
  vars:
    # created with:
    # python -c 'import crypt; print crypt.crypt("This is my Password", "$1$SomeSalt$")'
    password: $1$SomeSalt$UqddPX3r4kH3UL5jq5/ZI.
    user: jesbe
    storagehost: 192.168.130.251

  tasks:
# Create local users
  - name: Create Users
    user:
      name: "{{ item.name }}"
      password: "{{ item.pw }}"
    loop:
        - { 'name': 'user1', 'pw': '{{ password }}'}
        - { 'name': 'user2', 'pw': '{{ password }}'}
        - { 'name': 'user3', 'pw': '{{ password }}'}
        - { 'name': 'user4', 'pw': '{{ password }}'}
        - { 'name': 'user5', 'pw': '{{ password }}'}
        - { 'name': 'user6', 'pw': '{{ password }}'}        
        - { 'name': 'user7', 'pw': '{{ password }}'}
        - { 'name': 'user8', 'pw': '{{ password }}'}
        - { 'name': 'user9', 'pw': '{{ password }}'}
        - { 'name': 'user10', 'pw': '{{ password }}'}

# Create Ansible Hosts file
  - name: Create Ansible dir
    file:
      path: /etc/ansible
      state: directory
  
  - name: Touch Ansible hosts file
    file:
      path: /etc/ansible/hosts
      state: touch

  - name: Add servers to Ansible hosts file
    blockinfile:
      path: /etc/ansible/hosts
      block: |
        [storage]
        192.168.130.251
        [esxi]
        192.168.130.242

  - name: Install pip 9.0.3
    pip:
      name: pip==9.0.3