---
- hosts: localhost
  vars:
    hostname: 192.168.130.242
    username: root
    password: xxxxxx
    esxi_hostname: esxi.arrowdemo.local
  tasks:
  - name: Add local user to ESXi
    vmware_local_user_manager:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      local_user_name: "{{ item.name }}"
      local_user_password: "{{ item.pw }}"
      validate_certs: False
    delegate_to: localhost
    loop:
        - { 'name': 'user1', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user2', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user3', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user4', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user5', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user6', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user7', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user8', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user9', 'pw': 'P@s$w0rd!' }
        - { 'name': 'user10', 'pw': 'P@s$w0rd!' }

  - name: Add admin role to users in rootFolder
    vmware_object_role_permission:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      role: Admin
      principal: "{{ item.name }}"
      object_name: rootFolder
      state: present
    delegate_to: localhost
    loop:
        - { 'name': 'user1' }
        - { 'name': 'user2' }
        - { 'name': 'user3' }
        - { 'name': 'user4' }
        - { 'name': 'user5' }
        - { 'name': 'user6' }
        - { 'name': 'user7' }
        - { 'name': 'user8' }
        - { 'name': 'user9' }
        - { 'name': 'user10' }

  - name: Add a VMware vSwitch to a specific host system
    vmware_vswitch:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      esxi_hostname: "{{ esxi_hostname }}"
      switch_name: user_vswitch
      nic_name: vmnic1
      mtu: 9000
    delegate_to: localhost

  - name: Change NFS.MaxVolumes setting for an ESXi host
    vmware_host_config_manager:
      hostname: "{{ hostname }}"
      username: "{{ username }}"
      password: "{{ password }}"
      validate_certs: False
      esxi_hostname: "{{ esxi_hostname }}"
      options:
        'NFS.MaxVolumes': '16'
        'NFS41.MaxVolumes': '16'
    delegate_to: localhost