---
- hosts: localhost
  connection: local
  vars:
    location: northeurope
    virtualnetwork: TowerNetwork
    subnet: Servers
    rgname: TowerRG
    adminUser: awx
    ssh_public_key: "{{lookup('file', '~/.ssh/id_rsa.pub') }}"
    tag_owner: arrow
    tag_project: ansibleawx
    servers:
      - tower01
      - tower02

  tasks:
    - name: Azure Virtual Network
      include_role:
        name: jesperberth.az_virtualnetwork
      vars:
        resourcegroup: "{{ rgname }}"
        virtualnetwork_name: "{{ virtualnetwork }}"
        cidr: 10.1.0.0/16
        subnet_name: "{{ subnet }}"
        subnet_cidr: 10.1.0.0/24
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"

    - name: Azure Network Security Group
      include_role:
        name: jesperberth.az_securitygroup
      vars:
        resourcegroup: "{{ rgname }}"
        networksecuritygroup_name: "{{ item.networksecuritygroup_name }}"
        rulename: "{{ item.rulename }}"
        ruleprotocol: "{{ item.ruleprotocol }}"
        rulesourceaddress: "{{ item.rulesourceaddress }}"
        ruledestinationportrange: "{{ item.ruledestinationportrange }}"
        ruleaccess: "{{ item.ruleaccess }}"
        rulepriority: "{{ item.rulepriority }}"
        ruledirection: "{{ item.ruledirection }}"
        owner: "{{ tag_owner }}"
        project: "{{ tag_project }}"
      loop:
        - { networksecuritygroup_name: 'SG_Network', rulename: 'AllowSSH',  ruleprotocol: 'Tcp', rulesourceaddress: '0.0.0.0/0', ruledestinationportrange: '22', ruleaccess: 'Allow', rulepriority: '102', ruledirection: 'Inbound' }
        - { networksecuritygroup_name: 'SG_Network', rulename: 'AllowHTTP',  ruleprotocol: 'Tcp', rulesourceaddress: '0.0.0.0/0', ruledestinationportrange: '80', ruleaccess: 'Allow', rulepriority: '103', ruledirection: 'Inbound' }
        - { networksecuritygroup_name: 'SG_Network', rulename: 'AllowHTTPS',  ruleprotocol: 'Tcp', rulesourceaddress: '0.0.0.0/0', ruledestinationportrange: '443', ruleaccess: 'Allow', rulepriority: '104', ruledirection: 'Inbound' }

    - name: Create network interfaces
      azure_rm_networkinterface:
        name: "{{ item }}_nic01"
        resource_group: "{{ rgname }}"
        virtual_network: "{{ virtualnetwork }}"
        subnet_name: "{{ subnet }}"
        security_group: "SG_Network"
        ip_configurations:
          - name: "{{ item }}_nic01_ipconfig"
            public_ip_address_name: "{{ item }}_public_ip"
            primary: true
        tags:
          owner: "{{ tag_owner }}"
          project: "{{ tag_project }}"
      loop: "{{ servers }}"
      async: 1000
      poll: 0
      register: create_nic

    - name: Wait for Network Interfaces
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 5
      with_items: "{{ create_nic.results }}"

  # Create Virtual Machines
    - name: Create Virtual Machines
      azure_rm_virtualmachine:
        resource_group: "{{ rgname }}"
        name: "{{ item }}"
        os_type: "Linux"
        admin_username: "{{ adminUser }}"
        ssh_password_enabled: false
        ssh_public_keys:
          - path: "/home/{{ adminUser }}/.ssh/authorized_keys"
            key_data: "{{ ssh_public_key }}"
        managed_disk_type: Standard_LRS
        state: present
        image:
          offer: "RHEL"
          publisher: "RedHat"
          sku: "8"
          version: "latest"
        vm_size: "Standard_D2s_v3"
        network_interfaces: "{{ item }}_nic01"
        tags:
            owner: "{{ adminUser }}"
            project: "{{ tag_project }}"
      loop: "{{ servers }}"
      async: 1000
      poll: 0
      register: create_vm

    - name: Wait for Virtual Machines
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 100
      delay: 5
      with_items: "{{ create_vm.results }}"
