---
- name: AWX install on Enterprise Linux
  hosts: tag_project_ansibleawx
  become: true
  vars:
    ansible_user: awx
    awx_password: Passw0rd!
    awxoperater_version: "0.20.1"

  roles:
    - role: jesperberth.el_k3s
    - role: jesperberth.awx_k8s_install
